repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace # remove trailing whitespaces except markdown files
        args: [--markdown-linebreak-ext=md]
    -   id: end-of-file-fixer # add empty line at the end of files
    -   id: check-yaml # Check yaml
    -   id: check-added-large-files # Check if no file larger than 2MB has been added.
        args: ['--maxkb=2048']
-   repo: https://github.com/psf/black # Automatic code format
    rev: 22.12.0
    hooks:
    -   id: black
-   repo: https://github.com/hadialqattan/pycln # Clean unused imports
    rev: v2.1.3
    hooks:
    -   id: pycln
        args: ["-a", "-x", "-v"]
-   repo: https://github.com/pycqa/isort # Sort project imports
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile=black"]
-   repo: https://github.com/PyCQA/flake8 # Check code consistency
    rev: 6.0.0
    hooks:
    -   id: flake8
        args: ["--ignore=F541,N813,W503,W605,E203", "--max-line-length=120"]
-   repo: https://github.com/pycqa/pylint
    rev: v2.14.5
    hooks:
    -   id: pylint
        args: ["-E", "--disable=E0401", "--disable=E1101"]
